# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-17 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drafter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('player1', models.IntegerField()),
                ('player2', models.IntegerField()),
                ('player3', models.IntegerField()),
            ],
        ),
    ]
